//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MainResources", typeof(MainResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторизация.
        /// </summary>
        public static string AutorizationPageTitle {
            get {
                return ResourceManager.GetString("AutorizationPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string ButtonAdd {
            get {
                return ResourceManager.GetString("ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        public static string ButtonBack {
            get {
                return ResourceManager.GetString("ButtonBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить.
        /// </summary>
        public static string ButtonCancellationMessage {
            get {
                return ResourceManager.GetString("ButtonCancellationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить.
        /// </summary>
        public static string ButtonChange {
            get {
                return ResourceManager.GetString("ButtonChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string ButtonDeleteMessage {
            get {
                return ResourceManager.GetString("ButtonDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string ButtonSign {
            get {
                return ResourceManager.GetString("ButtonSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотреть.
        /// </summary>
        public static string ButtonView {
            get {
                return ResourceManager.GetString("ButtonView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотреть все регистрации.
        /// </summary>
        public static string ButtonViewAll {
            get {
                return ResourceManager.GetString("ButtonViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to нажмите сюда..
        /// </summary>
        public static string ClinicUserPageCancelRegistrationAfter {
            get {
                return ResourceManager.GetString("ClinicUserPageCancelRegistrationAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если Вы хотите отменить регистрацию, то.
        /// </summary>
        public static string ClinicUserPageCancelRegistrationBefore {
            get {
                return ResourceManager.GetString("ClinicUserPageCancelRegistrationBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to нажмите сюда..
        /// </summary>
        public static string ClinicUserPageRegistrationAfter {
            get {
                return ResourceManager.GetString("ClinicUserPageRegistrationAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если Вы хотите зарегистрировать место, то.
        /// </summary>
        public static string ClinicUserPageRegistrationBefore {
            get {
                return ResourceManager.GetString("ClinicUserPageRegistrationBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная страница.
        /// </summary>
        public static string ClinicUserPageTitle {
            get {
                return ResourceManager.GetString("ClinicUserPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to нажмите сюда..
        /// </summary>
        public static string ClinicUserPageViewNoticesAfter {
            get {
                return ResourceManager.GetString("ClinicUserPageViewNoticesAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если Вы хотите просмотреть ваши личные сообщения, то.
        /// </summary>
        public static string ClinicUserPageViewNoticesBefore {
            get {
                return ResourceManager.GetString("ClinicUserPageViewNoticesBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возраст:.
        /// </summary>
        public static string EmptyPlacePageAge {
            get {
                return ResourceManager.GetString("EmptyPlacePageAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество:.
        /// </summary>
        public static string EmptyPlacePageCount {
            get {
                return ResourceManager.GetString("EmptyPlacePageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пол:.
        /// </summary>
        public static string EmptyPlacePageSex {
            get {
                return ResourceManager.GetString("EmptyPlacePageSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить количество свободных мест для:.
        /// </summary>
        public static string EmptyPlacePageTableTitle {
            get {
                return ResourceManager.GetString("EmptyPlacePageTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка авторизации.
        /// </summary>
        public static string ErrorAuthorization_401 {
            get {
                return ResourceManager.GetString("ErrorAuthorization_401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страница не найдена.
        /// </summary>
        public static string ErrorPageIsNotFound_404 {
            get {
                return ResourceManager.GetString("ErrorPageIsNotFound_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заполнение завершено.
        /// </summary>
        public static string FillerLoadingMessage {
            get {
                return ResourceManager.GetString("FillerLoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to нажмите сюда..
        /// </summary>
        public static string HospitalUserPageChangeRegistrationAfter {
            get {
                return ResourceManager.GetString("HospitalUserPageChangeRegistrationAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если Вы хотите отредактировать список свободных мест, то .
        /// </summary>
        public static string HospitalUserPageChangeRegistrationBefore {
            get {
                return ResourceManager.GetString("HospitalUserPageChangeRegistrationBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to нажмите сюда..
        /// </summary>
        public static string HospitalUserPageSendMessageAfter {
            get {
                return ResourceManager.GetString("HospitalUserPageSendMessageAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если вы хотите разослать сообщения поликлиникам, то .
        /// </summary>
        public static string HospitalUserPageSendMessageBefore {
            get {
                return ResourceManager.GetString("HospitalUserPageSendMessageBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная страница.
        /// </summary>
        public static string HospitalUserPageTitle {
            get {
                return ResourceManager.GetString("HospitalUserPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to нажмите сюда..
        /// </summary>
        public static string HospitalUserPageViewComingRecordsAfter {
            get {
                return ResourceManager.GetString("HospitalUserPageViewComingRecordsAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если Вы хотите просмотреть список ближайших записей, то.
        /// </summary>
        public static string HospitalUserPageViewComingRecordsBefore {
            get {
                return ResourceManager.GetString("HospitalUserPageViewComingRecordsBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to нажмите сюда..
        /// </summary>
        public static string HospitalUserPageViewNoticesAfter {
            get {
                return ResourceManager.GetString("HospitalUserPageViewNoticesAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если Вы хотите просмотреть ваши личные сообщения, то.
        /// </summary>
        public static string HospitalUserPageViewNoticesBefore {
            get {
                return ResourceManager.GetString("HospitalUserPageViewNoticesBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить регистрацию.
        /// </summary>
        public static string MenuItemBreakClinicRegistration {
            get {
                return ResourceManager.GetString("MenuItemBreakClinicRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить регистрацию.
        /// </summary>
        public static string MenuItemChangeHospitalRegistrations {
            get {
                return ResourceManager.GetString("MenuItemChangeHospitalRegistrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        public static string MenuItemExit {
            get {
                return ResourceManager.GetString("MenuItemExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная страница.
        /// </summary>
        public static string MenuItemHomePage {
            get {
                return ResourceManager.GetString("MenuItemHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрировать.
        /// </summary>
        public static string MenuItemMakeClinicRegistration {
            get {
                return ResourceManager.GetString("MenuItemMakeClinicRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отметить прибывшего пациента.
        /// </summary>
        public static string MenuItemMarkClients {
            get {
                return ResourceManager.GetString("MenuItemMarkClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть регистрацию.
        /// </summary>
        public static string MenuItemOpenHospitalRegistrations {
            get {
                return ResourceManager.GetString("MenuItemOpenHospitalRegistrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разослать сообщения.
        /// </summary>
        public static string MenuItemSendDistributiveMessagesPage {
            get {
                return ResourceManager.GetString("MenuItemSendDistributiveMessagesPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить отметку.
        /// </summary>
        public static string MenuItemsUnmarkClients {
            get {
                return ResourceManager.GetString("MenuItemsUnmarkClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотреть сообщения.
        /// </summary>
        public static string MenuItemViewNotices {
            get {
                return ResourceManager.GetString("MenuItemViewNotices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        public static string NoticeTableDate {
            get {
                return ResourceManager.GetString("NoticeTableDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Личные сообщения.
        /// </summary>
        public static string NoticeTableHeading {
            get {
                return ResourceManager.GetString("NoticeTableHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор.
        /// </summary>
        public static string NoticeTableSender {
            get {
                return ResourceManager.GetString("NoticeTableSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тема.
        /// </summary>
        public static string NoticeTableTitle {
            get {
                return ResourceManager.GetString("NoticeTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить сообщения.
        /// </summary>
        public static string PageSendNoticesPageTitle {
            get {
                return ResourceManager.GetString("PageSendNoticesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to нажмите сюда..
        /// </summary>
        public static string ReceptionUserPageMarkPatientAfter {
            get {
                return ResourceManager.GetString("ReceptionUserPageMarkPatientAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если Вы хотите отметить прибывшего пациента, то .
        /// </summary>
        public static string ReceptionUserPageMarkPatientBefore {
            get {
                return ResourceManager.GetString("ReceptionUserPageMarkPatientBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная страница.
        /// </summary>
        public static string ReceptionUserPageTitle {
            get {
                return ResourceManager.GetString("ReceptionUserPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to нажмите сюда..
        /// </summary>
        public static string ReceptionUserPageUnmarkPatientAfter {
            get {
                return ResourceManager.GetString("ReceptionUserPageUnmarkPatientAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если Вы хотите отменить отметку, то.
        /// </summary>
        public static string ReceptionUserPageUnmarkPatientBefore {
            get {
                return ResourceManager.GetString("ReceptionUserPageUnmarkPatientBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить пароль.
        /// </summary>
        public static string SavePassword {
            get {
                return ResourceManager.GetString("SavePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здравствуйте.
        /// </summary>
        public static string UserPageHello {
            get {
                return ResourceManager.GetString("UserPageHello", resourceCulture);
            }
        }
    }
}
