//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MainResources", typeof(MainResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization Error.
        /// </summary>
        public static string ErrorAuthorization_401 {
            get {
                return ResourceManager.GetString("ErrorAuthorization_401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page is not found.
        /// </summary>
        public static string ErrorPageIsNotFound_404 {
            get {
                return ResourceManager.GetString("ErrorPageIsNotFound_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filling completed on.
        /// </summary>
        public static string FillerLoadingMessage {
            get {
                return ResourceManager.GetString("FillerLoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить регистрацию.
        /// </summary>
        public static string MenuItemBreakClinicRegistration {
            get {
                return ResourceManager.GetString("MenuItemBreakClinicRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить регистрацию.
        /// </summary>
        public static string MenuItemChangeHospitalRegistrations {
            get {
                return ResourceManager.GetString("MenuItemChangeHospitalRegistrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        public static string MenuItemExit {
            get {
                return ResourceManager.GetString("MenuItemExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string MenuItemHomePage {
            get {
                return ResourceManager.GetString("MenuItemHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрировать.
        /// </summary>
        public static string MenuItemMakeClinicRegistration {
            get {
                return ResourceManager.GetString("MenuItemMakeClinicRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть регистрацию.
        /// </summary>
        public static string MenuItemOpenHospitalRegistrations {
            get {
                return ResourceManager.GetString("MenuItemOpenHospitalRegistrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотреть сообщения.
        /// </summary>
        public static string MenuItemViewNotices {
            get {
                return ResourceManager.GetString("MenuItemViewNotices", resourceCulture);
            }
        }
    }
}
